#!/bin/bash
# delete obsolete pulseaudio sockets if left from previous sessions
rm -rf /home/chrome/.config/chrome-remote-desktop/pulseaudio*

# delete .Xauthority files possibly owned by root
rm -rf /home/chrome/.Xauthority*

# only keep 1 host#*.json config file
# (default is to use md5 of hostname, which changes on every docker run)
# if test -n "$(find /home/chrome/.config/chrome-remote-desktop -name 'host#*.json' -print -quit)"
# then
#   mv `ls -t /home/chrome/.config/chrome-remote-desktop/host#*.json | head -n 1` /home/chrome/.config/chrome-remote-desktop/~host.json
#   rm /home/chrome/.config/chrome-remote-desktop/host#*.json
#fi

rm -rf /home/chrome/.config/chrome-remote-desktop/*.json
